#!/usr/bin/env bash
#
# Generate an env file with a random free host-port block above 10000, for running this
# stack on a shared machine (or a second instance beside an existing one).
#
#   ./scripts/pick-ports.sh > .env.test
#   ENV_FILE=.env.test ./up.sh
#
# Only the values that must not collide are emitted; everything else falls back to the
# defaults baked into compose/core.yml and scripts/lib/common.sh. The COMPOSE_PROJECT_NAME
# is randomized too, because two stacks sharing a project name share their volumes.
#
set -euo pipefail

BASE_MIN=${BASE_MIN:-10100}
BASE_MAX=${BASE_MAX:-64000}
BLOCK=${BLOCK:-16}   # how many consecutive ports the block must cover

port_free() {
  # A port is usable only if nothing is listening AND docker can bind it. `nc -z` probes
  # the former; that is enough in practice since docker's own bind failure surfaces loudly.
  if command -v nc >/dev/null 2>&1; then
    ! nc -z 127.0.0.1 "$1" >/dev/null 2>&1
  else
    ! (exec 3<>"/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1
  fi
}

block_free() {
  local base="$1" i
  for (( i = 0; i < BLOCK; i++ )); do
    port_free $(( base + i )) || return 1
  done
  return 0
}

BASE=""
for _ in $(seq 1 200); do
  cand=$(( BASE_MIN + (RANDOM % (BASE_MAX - BASE_MIN - BLOCK)) ))
  cand=$(( cand - cand % 10 ))   # keep the block readable
  if block_free "$cand"; then BASE="$cand"; break; fi
done
[[ -z "$BASE" ]] && { echo "could not find a free ${BLOCK}-port block in ${BASE_MIN}-${BASE_MAX}" >&2; exit 1; }

SUFFIX="${SUFFIX:-$BASE}"
# PROJECT_PREFIX lets a caller mark what generated the stack — scripts/ci-check.sh uses
# `demo-infra-ci` so a leaked container is immediately attributable to a CI run rather than
# to somebody's laptop session.
PROJECT_PREFIX="${PROJECT_PREFIX:-demo-infra}"
IMAGE_TAG_SUFFIX="${IMAGE_TAG_SUFFIX:-${PROJECT_PREFIX}-${SUFFIX}}"

cat <<EOF
# Generated by scripts/pick-ports.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# A disposable, collision-free stack: random project name + a free port block at ${BASE}.
COMPOSE_PROJECT_NAME=${PROJECT_PREFIX}-${SUFFIX}

# Every locally built image gets a run-specific tag. Unique ports/volumes alone
# are not enough on a shared daemon: fixed :local tags can race or reuse stale
# binaries from another checkout.
POSTGRES_IMAGE=midnight-2-offers/postgres:${IMAGE_TAG_SUFFIX}
INDEXER_IMAGE=midnight-2-offers/indexer:${IMAGE_TAG_SUFFIX}
EVM_IMAGE=midnight-2-offers/umbra-evm:${IMAGE_TAG_SUFFIX}
CELESTIA_IMAGE=midnight-2-offers/celestia:${IMAGE_TAG_SUFFIX}
KERNEL_IMAGE=midnight-2-offers/offerfiles-kernel:${IMAGE_TAG_SUFFIX}
FRONTEND_IMAGE=midnight-2-offers/zswap-da:${IMAGE_TAG_SUFFIX}
AA_IMAGE=midnight-2-offers/aa-contracts:${IMAGE_TAG_SUFFIX}
AA_CONSOLE_IMAGE=midnight-2-offers/aa-contracts:${IMAGE_TAG_SUFFIX}-console
AA_E2E_IMAGE=midnight-2-offers/aa-contracts:${IMAGE_TAG_SUFFIX}-e2e
SOLVER_IMAGE=midnight-2-offers/cow-solver:${IMAGE_TAG_SUFFIX}
SOLVER_SINK_IMAGE=midnight-2-offers/cow-solver-sink:${IMAGE_TAG_SUFFIX}

NODE_TAG=${NODE_TAG:-2.0.0-rc.4}
INDEXER_REF=${INDEXER_REF:-56561b2f5cf5c6839f678257fc69bed1a8b9ba2c}
INDEXER_RUST_VERSION=${INDEXER_RUST_VERSION:-1.95.0}
PROOF_TAG=${PROOF_TAG:-9.0.0-rc.5}
TOOLKIT_TAG=${TOOLKIT_TAG:-2.0.0-rc.4}
INDEXER_PLATFORM=${INDEXER_PLATFORM:-linux/amd64}

BIND_ADDR=127.0.0.1
NODE_HOST_PORT=$(( BASE + 0 ))
INDEXER_HOST_PORT=$(( BASE + 1 ))
PROOF_HOST_PORT=$(( BASE + 2 ))

EVM_RPC_HOST_PORT=$(( BASE + 3 ))
EVM_WS_HOST_PORT=$(( BASE + 4 ))
KERNEL_HOST_PORT=$(( BASE + 5 ))
BATCHER_HOST_PORT=$(( BASE + 6 ))
CELESTIA_HOST_PORT=$(( BASE + 7 ))
FRONTEND_HOST_PORT=$(( BASE + 8 ))
AA_CONSOLE_HOST_PORT=$(( BASE + 9 ))
SOLVER_SINK_HOST_PORT=$(( BASE + 10 ))
SOLVER_RELAY_HOST_PORT=$(( BASE + 11 ))

# The SPA's hostname-relative fallback is valid only on the default :9999/:3334
# layout. A generated random-port stack must inject its actual host endpoints.
FRONTEND_API_BASE=http://127.0.0.1:$(( BASE + 5 ))
FRONTEND_BATCHER_URL=http://127.0.0.1:$(( BASE + 6 ))

INDEXER_SECRET=303132333435363738393031323334353637383930313233343536373839303132

NODE_WAIT_TIMEOUT=${NODE_WAIT_TIMEOUT:-180}
INDEXER_WAIT_TIMEOUT=${INDEXER_WAIT_TIMEOUT:-420}
PROOF_WAIT_TIMEOUT=${PROOF_WAIT_TIMEOUT:-120}
EVM_WAIT_TIMEOUT=${EVM_WAIT_TIMEOUT:-300}
CELESTIA_WAIT_TIMEOUT=${CELESTIA_WAIT_TIMEOUT:-300}
SOLVER_WAIT_TIMEOUT=${SOLVER_WAIT_TIMEOUT:-300}
EOF
