#!/usr/bin/env bash
#
# Generate an env file with a random free host-port block above 10000, for running this
# stack on a shared machine (or a second instance beside an existing one).
#
#   ./scripts/pick-ports.sh > .env.test
#   ENV_FILE=.env.test ./up.sh
#
# Only the values that must not collide are emitted; everything else falls back to the
# defaults baked into compose/core.yml and scripts/lib/common.sh. The COMPOSE_PROJECT_NAME
# is randomized too, because two stacks sharing a project name share their volumes.
#
set -euo pipefail

BASE_MIN=${BASE_MIN:-10100}
BASE_MAX=${BASE_MAX:-64000}
BLOCK=${BLOCK:-16}   # how many consecutive ports the block must cover

port_free() {
  # A port is usable only if nothing is listening AND docker can bind it. `nc -z` probes
  # the former; that is enough in practice since docker's own bind failure surfaces loudly.
  if command -v nc >/dev/null 2>&1; then
    ! nc -z 127.0.0.1 "$1" >/dev/null 2>&1
  else
    ! (exec 3<>"/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1
  fi
}

block_free() {
  local base="$1" i
  for (( i = 0; i < BLOCK; i++ )); do
    port_free $(( base + i )) || return 1
  done
  return 0
}

BASE=""
for _ in $(seq 1 200); do
  cand=$(( BASE_MIN + (RANDOM % (BASE_MAX - BASE_MIN - BLOCK)) ))
  cand=$(( cand - cand % 10 ))   # keep the block readable
  if block_free "$cand"; then BASE="$cand"; break; fi
done
[[ -z "$BASE" ]] && { echo "could not find a free ${BLOCK}-port block in ${BASE_MIN}-${BASE_MAX}" >&2; exit 1; }

SUFFIX="${SUFFIX:-$BASE}"
# PROJECT_PREFIX lets a caller mark what generated the stack — scripts/ci-check.sh uses
# `demo-infra-ci` so a leaked container is immediately attributable to a CI run rather than
# to somebody's laptop session.
PROJECT_PREFIX="${PROJECT_PREFIX:-demo-infra}"
IMAGE_TAG_SUFFIX="${IMAGE_TAG_SUFFIX:-${PROJECT_PREFIX}-${SUFFIX}}"

cat <<EOF
# Generated by scripts/pick-ports.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# A disposable, collision-free stack: random project name + a free port block at ${BASE}.
COMPOSE_PROJECT_NAME=${PROJECT_PREFIX}-${SUFFIX}

# Every locally built image gets a run-specific tag. Unique ports/volumes alone
# are not enough on a shared daemon: fixed :local tags can race or reuse stale
# binaries from another checkout.
POSTGRES_IMAGE=midnight-2-offers/postgres:${IMAGE_TAG_SUFFIX}
INDEXER_IMAGE=midnight-2-offers/indexer:${IMAGE_TAG_SUFFIX}
PROOF_PARAMS_IMAGE=midnight-2-offers/proof-params:${IMAGE_TAG_SUFFIX}
EVM_IMAGE=midnight-2-offers/umbra-evm:${IMAGE_TAG_SUFFIX}
CELESTIA_IMAGE=midnight-2-offers/celestia:${IMAGE_TAG_SUFFIX}
KERNEL_IMAGE=midnight-2-offers/offerfiles-kernel:${IMAGE_TAG_SUFFIX}
FRONTEND_IMAGE=midnight-2-offers/zswap-da:${IMAGE_TAG_SUFFIX}
AA_IMAGE=midnight-2-offers/aa-contracts:${IMAGE_TAG_SUFFIX}
AA_CONSOLE_IMAGE=midnight-2-offers/aa-contracts:${IMAGE_TAG_SUFFIX}-console
AA_E2E_IMAGE=midnight-2-offers/aa-contracts:${IMAGE_TAG_SUFFIX}-e2e
SOLVER_IMAGE=midnight-2-offers/cow-solver:${IMAGE_TAG_SUFFIX}
SOLVER_SINK_IMAGE=midnight-2-offers/cow-solver-sink:${IMAGE_TAG_SUFFIX}
# ONE build context, TWO runtime targets (nginx page server + bun deploy/verify one-shot), so
# two image names. Both must carry the run-specific tag or a second stack on this daemon would
# reuse the first one's binaries.
SHIELDED_NIGHT_IMAGE=midnight-2-offers/shielded-night:${IMAGE_TAG_SUFFIX}
SHIELDED_NIGHT_DEPLOY_IMAGE=midnight-2-offers/shielded-night-deploy:${IMAGE_TAG_SUFFIX}

# External runtime images: repository + IMMUTABLE DIGEST, never a tag. Node and toolkit are
# the official multiarch images; both proof-server variants come from the Effectstream GHCR
# mirror, which is byte-identical to the upstream indexes. Readable versions are in the
# comments — 2.0.0-rc.4 (node, toolkit) and 9.0.0-rc.5 plain / 9.0.0-rc.5 experimental.
NODE_IMAGE=${NODE_IMAGE:-docker.io/midnightntwrk/midnight-node@sha256:caf93d6f9fb3630c906ef3e714c151655377f3d28f907d17545de1870514da2e}
TOOLKIT_IMAGE=${TOOLKIT_IMAGE:-docker.io/midnightntwrk/midnight-node-toolkit@sha256:c3efb50d483b1216e9582669038dc6d2fac509b33d11ebc0b4e0d0d0b86b4d0f}
PROOF_IMAGE=${PROOF_IMAGE:-ghcr.io/effectstream/midnight-proof-server@sha256:d96a4d0f3f0f10f82698288443f2873a32fed180eb8f93c0bae83572c0a187a9}
AA_PROOF_IMAGE=${AA_PROOF_IMAGE:-ghcr.io/effectstream/midnight-proof-server@sha256:4f02ca2734649eb238d13924df299b1c82bd5546ec928c5d67bdd0ce86dd0bd1}

# The shared proof-data generation both proof servers mount read-only.
PROOF_DATA_GENERATION=${PROOF_DATA_GENERATION:-b73584978fc560bb827fd9df3ad914b37a6f5ea434fe62e9fa0adad809d8486c}

# Warehouse-backed binaries (indexer + Celestia). Which release, never which bytes: the
# SHA-256 pins live in the image Dockerfiles and config/artifact-decisions.json.
WAREHOUSE_REPO=${WAREHOUSE_REPO:-effectstream/binaries}
WAREHOUSE_RELEASE=${WAREHOUSE_RELEASE:-0.3.120}
INDEXER_VERSION=${INDEXER_VERSION:-4.4.0-rc.3}

BIND_ADDR=127.0.0.1
NODE_HOST_PORT=$(( BASE + 0 ))
INDEXER_HOST_PORT=$(( BASE + 1 ))
PROOF_HOST_PORT=$(( BASE + 2 ))

EVM_RPC_HOST_PORT=$(( BASE + 3 ))
EVM_WS_HOST_PORT=$(( BASE + 4 ))
KERNEL_HOST_PORT=$(( BASE + 5 ))
BATCHER_HOST_PORT=$(( BASE + 6 ))
CELESTIA_HOST_PORT=$(( BASE + 7 ))
FRONTEND_HOST_PORT=$(( BASE + 8 ))
AA_CONSOLE_HOST_PORT=$(( BASE + 9 ))
SOLVER_SINK_HOST_PORT=$(( BASE + 10 ))
SOLVER_RELAY_HOST_PORT=$(( BASE + 11 ))
SHIELDED_NIGHT_HOST_PORT=$(( BASE + 12 ))

# The SPA's hostname-relative fallback is valid only on the default :9999/:3334
# layout. A generated random-port stack must inject its actual host endpoints.
FRONTEND_API_BASE=http://127.0.0.1:$(( BASE + 5 ))
FRONTEND_BATCHER_URL=http://127.0.0.1:$(( BASE + 6 ))

INDEXER_SECRET=303132333435363738393031323334353637383930313233343536373839303132

NODE_WAIT_TIMEOUT=${NODE_WAIT_TIMEOUT:-180}
INDEXER_WAIT_TIMEOUT=${INDEXER_WAIT_TIMEOUT:-420}
PROOF_WAIT_TIMEOUT=${PROOF_WAIT_TIMEOUT:-120}
EVM_WAIT_TIMEOUT=${EVM_WAIT_TIMEOUT:-300}
CELESTIA_WAIT_TIMEOUT=${CELESTIA_WAIT_TIMEOUT:-300}
SOLVER_WAIT_TIMEOUT=${SOLVER_WAIT_TIMEOUT:-300}
# The shielded-night page starts only after TWO one-shots: a toolkit funding pass (NIGHT +
# DUST registration + a wait for a spendable DUST UTXO) and a real contract deploy proved on a
# cold chain. On the 2.x line proving runs 1.25-1.6x slower than on 1.x, so this is minutes.
SHIELDED_NIGHT_WAIT_TIMEOUT=${SHIELDED_NIGHT_WAIT_TIMEOUT:-900}
EOF
