#!/usr/bin/env python3
"""render-readme-pins.py — the README's "Where every component comes from" table is
GENERATED from the repository's real pins, never typed by hand.

Why: a pin table written by hand drifts the first time a ref is bumped in compose/
and nobody remembers the README. This script reads the values that actually build
the stack and renders the table between two markers in README.md; `--check` (the
default, wired into scripts/ci-check.sh) fails when the committed README no longer
matches what the pins say.

What is read (and only this — nothing is fetched, nothing is built):
  * config/artifact-decisions.json   digest-pinned images and warehouse binaries
                                     (versions, index digests, the warehouse tag)
  * compose/*.yml                    `${NAME:-<value>}` build-arg defaults
  * images/**/Dockerfile             `ARG NAME=<value>` defaults
  * .env.example                     `NAME=<value>`, commented or not
  * scripts/*.sh                     `${NAME:-<value>}` expectations
  * config/readme-components.json    the rows: prose columns plus placeholders

A source pin that has TWO different defaults in the tree is an error, not a choice:
the table cannot say which one the image was built from, and neither can you.

Placeholders (inside any cell of config/readme-components.json):
  {version:<component-id>}       version from artifact-decisions.json
  {oci:<component-id>}           short index digest (official or mirror destination)
  {prov:<component-id>}          linked short commit of a warehouse binary's
                                 sourceProvenance (provenance only, never built)
  {warehouse}                    `<repo>@<releaseTag>` of the binary warehouse
  {warehouse-url}                its GitHub release URL
  {ref:<NAME>}                   short (12-hex) default of source pin NAME
  {full:<NAME>}                  the full default of NAME
  {commit:<NAME>@<owner/repo>}   short default of NAME linked to that commit
  {files:<NAME>[,<NAME>…]}       every file that declares a default for those pins

Usage:
  scripts/render-readme-pins.py             --check: README matches the pins (exit 1 + diff)
  scripts/render-readme-pins.py --write     rewrite the block in README.md
  scripts/render-readme-pins.py --print     the rendered table on stdout
  scripts/render-readme-pins.py --self-test prove --check can FAIL: copy the tree,
                                            split one pin, assert non-zero; strip the
                                            markers, assert non-zero; untouched passes.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import shutil
import sys
import tempfile
from pathlib import Path

MARKER = "render-readme-pins"
BEGIN_RE = re.compile(rf"^<!-- {MARKER}:begin\b.*?-->\n", re.M)
END_RE = re.compile(rf"^<!-- {MARKER}:end -->\n?", re.M)
BEGIN_LINE = (
    f"<!-- {MARKER}:begin — GENERATED by scripts/render-readme-pins.py --write "
    "from compose/, images/, .env.example and config/artifact-decisions.json. "
    "Edit config/readme-components.json, not this block. -->\n"
)
END_LINE = f"<!-- {MARKER}:end -->\n"

# What a default may look like: a 40-hex commit, a 64-hex SHA-256, or a version /
# release tag. Anything else in a `${NAME:-…}` is a runtime knob, not a pin.
VALUE_RE = r"(?:[0-9a-fA-F]{40}|[0-9a-fA-F]{64}|v?[0-9]+(?:[.\-+][0-9A-Za-z]+)*)"
PLACEHOLDER_RE = re.compile(r"\{([a-z-]+)(?::([^}]*))?\}")


class RenderError(Exception):
    pass


# ── pin collection ───────────────────────────────────────────────────────────

def scan_files(root: Path) -> list[Path]:
    out: list[Path] = []
    env = root / ".env.example"
    if env.is_file():
        out.append(env)
    for sub, pats in (("compose", ("*.yml", "*.yaml")), ("images", ("Dockerfile", "Dockerfile.*")), ("scripts", ("*.sh",))):
        base = root / sub
        if base.is_dir():
            for pat in pats:
                out.extend(p for p in base.rglob(pat) if p.is_file())
    return sorted(set(out))


def collect_defaults(root: Path, names: set[str]) -> dict[str, dict[str, set[str]]]:
    """name -> {value -> {repo-relative file, …}} over every place a default lives."""
    found: dict[str, dict[str, set[str]]] = {n: {} for n in names}
    if not names:
        return found
    alt = "|".join(re.escape(n) for n in sorted(names))
    # `${NAME:-value}` in compose and scripts, and bash's `${NAME:=value}` assign-default too
    compose_re = re.compile(rf"\$\{{({alt}):[-=]({VALUE_RE})\}}")
    arg_re = re.compile(rf"^\s*ARG\s+({alt})=({VALUE_RE})\s*$", re.M)
    env_re = re.compile(rf"^\s*#?\s*({alt})=({VALUE_RE})\s*$", re.M)
    for path in scan_files(root):
        text = path.read_text(encoding="utf-8", errors="replace")
        rel = path.relative_to(root).as_posix()
        hits = list(compose_re.finditer(text))
        if path.name.startswith("Dockerfile"):
            hits += list(arg_re.finditer(text))
        if path.name == ".env.example":
            hits += list(env_re.finditer(text))
        for m in hits:
            found[m.group(1)].setdefault(m.group(2).lower(), set()).add(rel)
    return found


# ── placeholder resolution ───────────────────────────────────────────────────

class Resolver:
    def __init__(self, root: Path, matrix: dict, defaults: dict[str, dict[str, set[str]]]):
        self.root = root
        self.matrix = matrix
        self.defaults = defaults
        self.components = {c["id"]: c for c in matrix.get("components", [])}

    def component(self, cid: str) -> dict:
        try:
            return self.components[cid]
        except KeyError:
            raise RenderError(f"{{…:{cid}}}: no component '{cid}' in config/artifact-decisions.json") from None

    def value(self, name: str) -> tuple[str, set[str]]:
        vals = self.defaults.get(name) or {}
        if not vals:
            raise RenderError(f"{name}: no default found in compose/, images/, scripts/ or .env.example")
        if len(vals) != 1:
            lines = [f"{name}: {len(vals)} DIFFERENT defaults — a pin with two values is not a pin"]
            for v, files in sorted(vals.items()):
                lines.append(f"    {v}  {' '.join(sorted(files))}")
            raise RenderError("\n".join(lines))
        (v, files), = vals.items()
        return v, files

    @staticmethod
    def short(v: str) -> str:
        v = v.removeprefix("sha256:")
        return v[:12] + "…" if re.fullmatch(r"[0-9a-f]{40,64}", v) else v

    def resolve(self, kind: str, arg: str | None) -> str:
        if kind == "version":
            return str(self.component(arg)["version"])
        if kind == "oci":
            c = self.component(arg)
            digest = (c.get("oci") or {}).get("indexDigest") or (c.get("destination") or {}).get("indexDigest")
            if not digest:
                raise RenderError(f"{{oci:{arg}}}: component has no oci.indexDigest / destination.indexDigest")
            return f"`{self.short(digest)}`"
        if kind == "prov":
            c = self.component(arg)
            p = c.get("sourceProvenance") or {}
            if not p.get("repository") or not p.get("commit"):
                raise RenderError(f"{{prov:{arg}}}: component has no sourceProvenance.repository/commit")
            return f"[`{p['repository']}@{p['commit'][:12]}`](https://github.com/{p['repository']}/commit/{p['commit']})"
        if kind == "warehouse":
            w = self.matrix.get("warehouse") or {}
            return f"`{w.get('repository')}@{w.get('releaseTag')}`"
        if kind == "warehouse-url":
            w = self.matrix.get("warehouse") or {}
            return f"https://github.com/{w.get('repository')}/releases/tag/{w.get('releaseTag')}"
        if kind == "ref":
            return f"`{self.short(self.value(arg)[0])}`"
        if kind == "full":
            return self.value(arg)[0]
        if kind == "commit":
            name, _, repo = arg.partition("@")
            if not repo:
                raise RenderError(f"{{commit:{arg}}}: expected {{commit:NAME@owner/repo}}")
            v, _ = self.value(name)
            if not re.fullmatch(r"[0-9a-f]{40}", v):
                raise RenderError(f"{{commit:{arg}}}: {name}={v} is not a 40-hex commit")
            return f"[`{v[:12]}`](https://github.com/{repo}/commit/{v})"
        if kind == "files":
            files: set[str] = set()
            for name in arg.split(","):
                files |= self.value(name.strip())[1]
            return " · ".join(f"`{f}`" for f in sorted(files))
        raise RenderError(f"unknown placeholder {{{kind}}}")

    def render_cell(self, text: str) -> str:
        return PLACEHOLDER_RE.sub(lambda m: self.resolve(m.group(1), m.group(2)), text)


# ── rendering ────────────────────────────────────────────────────────────────

def placeholder_names(cfg: dict) -> set[str]:
    names: set[str] = set()
    for row in cfg["rows"]:
        for cell in row.values():
            for m in PLACEHOLDER_RE.finditer(str(cell)):
                kind, arg = m.group(1), m.group(2) or ""
                if kind in ("ref", "full"):
                    names.add(arg)
                elif kind == "commit":
                    names.add(arg.partition("@")[0])
                elif kind == "files":
                    names |= {n.strip() for n in arg.split(",")}
    for group in cfg.get("mustBeEqual", []):
        names |= set(group)
    return names


def render(root: Path) -> str:
    cfg = json.loads((root / "config" / "readme-components.json").read_text(encoding="utf-8"))
    matrix = json.loads((root / "config" / "artifact-decisions.json").read_text(encoding="utf-8"))
    defaults = collect_defaults(root, placeholder_names(cfg))
    r = Resolver(root, matrix, defaults)
    for group in cfg.get("mustBeEqual", []):
        vals = {n: r.value(n)[0] for n in group}
        if len(set(vals.values())) != 1:
            raise RenderError("these pins must be equal but are not: " + ", ".join(f"{k}={v[:12]}" for k, v in vals.items()))
    cols = cfg["columns"]  # [{"key": "component", "title": "Component"}, …]
    out = ["| " + " | ".join(c["title"] for c in cols) + " |", "|" + "---|" * len(cols)]
    for row in cfg["rows"]:
        cells = [r.render_cell(str(row.get(c["key"], ""))).replace("\n", " ") for c in cols]
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out) + "\n"


def split_readme(text: str) -> tuple[str, str, str]:
    b = BEGIN_RE.search(text)
    e = END_RE.search(text)
    if not b or not e or e.start() < b.end():
        raise RenderError(f"README.md has no `<!-- {MARKER}:begin -->` … `<!-- {MARKER}:end -->` block")
    return text[: b.start()], text[b.end(): e.start()], text[e.end():]


def check(root: Path) -> int:
    readme = root / "README.md"
    _, current, _ = split_readme(readme.read_text(encoding="utf-8"))
    wanted = render(root)
    if current == wanted:
        print(f"OK   README.md pin table matches the pins ({wanted.count(chr(10)) - 2} rows)")
        return 0
    print("FAIL README.md pin table is stale — run scripts/render-readme-pins.py --write", file=sys.stderr)
    sys.stderr.writelines(difflib.unified_diff(
        current.splitlines(True), wanted.splitlines(True), "README.md (committed)", "README.md (rendered)"))
    return 1


def write(root: Path) -> int:
    readme = root / "README.md"
    head, current, tail = split_readme(readme.read_text(encoding="utf-8"))
    wanted = render(root)
    readme.write_text(head + BEGIN_LINE + wanted + END_LINE + tail, encoding="utf-8")
    print(("updated" if current != wanted else "unchanged") + " README.md pin table")
    return 0


# ── self-test ────────────────────────────────────────────────────────────────

def _copy_tree(root: Path, dst: Path) -> None:
    for item in ("compose", "images", "scripts", "config"):
        if (root / item).exists():
            shutil.copytree(root / item, dst / item)
    for f in (".env.example", "README.md"):
        if (root / f).exists():
            shutil.copy2(root / f, dst / f)


def _quiet_check(root: Path) -> int:
    import contextlib, io
    with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
        try:
            return check(root)
        except RenderError:
            return 1


def self_test(root: Path) -> int:
    cfg = json.loads((root / "config" / "readme-components.json").read_text(encoding="utf-8"))
    names = placeholder_names(cfg)
    victim = next((n for n in sorted(names) if n.endswith("_REF")), None)
    if victim is None:
        print("FAIL self-test: no *_REF placeholder to split", file=sys.stderr)
        return 1
    with tempfile.TemporaryDirectory() as tmp:
        t = Path(tmp) / "tree"
        _copy_tree(root, t)
        if _quiet_check(t) != 0:
            print("FAIL self-test 1/3: the untouched copy does not pass — run --check to see why", file=sys.stderr)
            check(t)
            return 1
        print("OK   self-test 1/3: untouched copy passes")

        # 2. split ONE default of a source pin: the render must refuse, so --check fails.
        pat = re.compile(rf"\$\{{{victim}:-[0-9a-f]{{40}}\}}")
        for yml in sorted((t / "compose").glob("*.yml")):
            text = yml.read_text(encoding="utf-8")
            if pat.search(text):
                yml.write_text(pat.sub("${" + victim + ":-0123456789abcdef0123456789abcdef01234567}", text, count=1), encoding="utf-8")
                break
        else:
            print(f"FAIL self-test: no compose default for {victim} to split", file=sys.stderr)
            return 1
        if _quiet_check(t) == 0:
            print(f"FAIL self-test 2/3: a split {victim} still passed", file=sys.stderr)
            return 1
        print(f"OK   self-test 2/3: a split {victim} default is caught")

        # 3. a README without the markers cannot be checked, so it fails.
        shutil.rmtree(t)
        _copy_tree(root, t)
        readme = t / "README.md"
        readme.write_text(BEGIN_RE.sub("", END_RE.sub("", readme.read_text(encoding="utf-8"))), encoding="utf-8")
        if _quiet_check(t) == 0:
            print("FAIL self-test 3/3: a README without markers still passed", file=sys.stderr)
            return 1
        print("OK   self-test 3/3: a README without the markers is caught")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--check", action="store_true", help="(default) fail if README.md does not match the pins")
    g.add_argument("--write", action="store_true", help="rewrite the block in README.md")
    g.add_argument("--print", action="store_true", help="print the rendered table")
    g.add_argument("--self-test", action="store_true", help="prove --check can fail")
    ap.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    a = ap.parse_args()
    try:
        if a.write:
            return write(a.root)
        if a.print:
            sys.stdout.write(render(a.root))
            return 0
        if a.self_test:
            return self_test(a.root)
        return check(a.root)
    except RenderError as e:
        print(f"FAIL {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
